name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone -b master --depth 1 https://github.com/padavanonly/immortalwrt
    REPO_NAME: immortalwrt

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone immortalwrt repo
              run: |
                  $CLONE_COMMAND

            - name: Copy config to source code
              run: |
                  cp -f .config diy.sh $REPO_NAME/

            - name: Get the dependency of immortalwrt
              run: |
                  cd $REPO_NAME
                  ./scripts/feeds update -a && ./scripts/feeds install -a
                  chmod +x diy.sh
                  ./diy.sh

            - name: Upload config before build
              uses: actions/upload-artifact@v3
              with:
                  name: config before build
                  path: .config

            - name: Build immortalwrt
              run: |
                  cd $REPO_NAME
                  make -j$(nproc) || make -j1 V=s

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: targets
